import type { WardrobeData } from "@/lib/types";

const image = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=82`;

export const seedData: WardrobeData = {
  stores: [
    {
      id: "store-1",
      name: "COS",
      isArchived: false,
      type: "both",
      url: "https://www.cos.com",
      location: "Citystars, Cairo",
      photo: image("photo-1441986300917-64674bd600d8"),
      note: "Reliable minimal basics. Wait for the seasonal sale.",
      createdAt: "2026-01-04T09:00:00.000Z",
    },
    {
      id: "store-2",
      name: "Local Loom",
      isArchived: false,
      type: "online",
      url: "https://example.com",
      location: "Cairo",
      photo: image("photo-1528698827591-e19ccd7bc23d"),
      note: "Great natural fabrics and relaxed cuts.",
      createdAt: "2026-02-10T09:00:00.000Z",
    },
    {
      id: "store-3",
      name: "Massimo Dutti",
      isArchived: false,
      type: "both",
      url: "https://www.massimodutti.com",
      location: "Mall of Egypt",
      photo: image("photo-1521335629791-ce4aec67dd47"),
      note: "Best for workwear and leather shoes.",
      createdAt: "2026-02-18T09:00:00.000Z",
    },
  ],
  items: [
    {
      id: "item-1",
      name: "Everyday white tee",
      isArchived: false,
      category: "top",
      type: "T-shirt",
      primaryColor: "White",
      size: "M",
      material: "Organic cotton",
      formalityScore: 1,
      warmthLevel: "light",
      ownershipStatus: "own",
      needsAttention: false,
      satisfactionRating: 5,
      price: 890,
      acquiredDate: "2026-01-18",
      sourceStoreId: "store-1",
      candidateStoreIds: [],
      note: "Soft, slightly boxy fit. The default.",
      photos: [image("photo-1521572163474-6864f9cf17ab")],
      createdAt: "2026-01-18T10:00:00.000Z",
    },
    {
      id: "item-2",
      name: "Ink linen shirt",
      isArchived: false,
      category: "top",
      type: "Shirt",
      primaryColor: "Navy",
      size: "M",
      material: "Linen",
      formalityScore: 3,
      warmthLevel: "light",
      ownershipStatus: "own",
      needsAttention: false,
      satisfactionRating: 5,
      price: 2200,
      acquiredDate: "2026-03-05",
      sourceStoreId: "store-2",
      candidateStoreIds: [],
      note: "Works tucked or open over a tee.",
      photos: [image("photo-1598033129183-c4f50c736f10")],
      createdAt: "2026-03-05T10:00:00.000Z",
    },
    {
      id: "item-3",
      name: "Straight blue denim",
      isArchived: false,
      category: "bottom",
      type: "Jeans",
      primaryColor: "Blue",
      size: "31/30",
      material: "Denim",
      formalityScore: 2,
      warmthLevel: "medium",
      ownershipStatus: "own",
      needsAttention: false,
      satisfactionRating: 4,
      price: 2400,
      acquiredDate: "2025-11-22",
      sourceStoreId: "store-1",
      candidateStoreIds: [],
      note: "Clean straight leg. Best after one cuff.",
      photos: [image("photo-1542272604-787c3835535d")],
      createdAt: "2025-11-22T10:00:00.000Z",
    },
    {
      id: "item-4",
      name: "Sand pleated trousers",
      isArchived: false,
      category: "bottom",
      type: "Trousers",
      primaryColor: "Beige",
      size: "32",
      material: "Cotton twill",
      formalityScore: 4,
      warmthLevel: "medium",
      ownershipStatus: "own",
      needsAttention: true,
      satisfactionRating: 4,
      price: 2900,
      acquiredDate: "2026-02-02",
      sourceStoreId: "store-3",
      candidateStoreIds: [],
      note: "Hem needs shortening by about 2 cm.",
      photos: [image("photo-1506629082955-511b1aa562c8")],
      createdAt: "2026-02-02T10:00:00.000Z",
    },
    {
      id: "item-5",
      name: "Olive field jacket",
      isArchived: false,
      category: "outerwear",
      type: "Jacket",
      primaryColor: "Olive",
      size: "M",
      material: "Waxed cotton",
      formalityScore: 2,
      warmthLevel: "medium",
      ownershipStatus: "own",
      needsAttention: false,
      satisfactionRating: 5,
      price: 3800,
      acquiredDate: "2025-10-09",
      sourceStoreId: "store-2",
      candidateStoreIds: [],
      note: "Perfect layer for cool evenings.",
      photos: [image("photo-1551028719-00167b16eac5")],
      createdAt: "2025-10-09T10:00:00.000Z",
    },
    {
      id: "item-6",
      name: "Chocolate loafers",
      isArchived: false,
      category: "shoes",
      type: "Loafers",
      primaryColor: "Brown",
      size: "42 EU",
      material: "Leather",
      formalityScore: 4,
      warmthLevel: "medium",
      ownershipStatus: "own",
      needsAttention: false,
      satisfactionRating: 4,
      price: 4500,
      acquiredDate: "2026-01-12",
      sourceStoreId: "store-3",
      candidateStoreIds: [],
      note: "Comfortable after breaking in.",
      photos: [image("photo-1549298916-b41d501d3772")],
      createdAt: "2026-01-12T10:00:00.000Z",
    },
    {
      id: "item-7",
      name: "White court sneakers",
      isArchived: false,
      category: "shoes",
      type: "Sneakers",
      primaryColor: "White",
      size: "42 EU",
      material: "Leather",
      formalityScore: 2,
      warmthLevel: "light",
      ownershipStatus: "own",
      needsAttention: true,
      satisfactionRating: 5,
      price: 3200,
      acquiredDate: "2025-08-20",
      sourceStoreId: "store-1",
      candidateStoreIds: [],
      note: "Needs a proper clean before next wear.",
      photos: [image("photo-1542291026-7eec264c27ff")],
      createdAt: "2025-08-20T10:00:00.000Z",
    },
    {
      id: "item-8",
      name: "Soft black blazer",
      isArchived: false,
      category: "outerwear",
      type: "Blazer",
      primaryColor: "Black",
      size: "48 EU",
      material: "Wool blend",
      formalityScore: 5,
      warmthLevel: "medium",
      ownershipStatus: "want",
      needsAttention: false,
      satisfactionRating: 0,
      price: 6500,
      acquiredDate: "",
      sourceStoreId: null,
      candidateStoreIds: ["store-1", "store-3"],
      note: "Unstructured shoulders, ideally single-button.",
      photos: [image("photo-1507679799987-c73779587ccf")],
      createdAt: "2026-04-08T10:00:00.000Z",
    },
  ],
  outfits: [
    {
      id: "outfit-1",
      name: "Easy Thursday",
      isArchived: false,
      occasion: "work",
      isDraft: false,
      itemIds: ["item-2", "item-4", "item-6"],
      createdAt: "2026-08-04T10:00:00.000Z",
    },
    {
      id: "outfit-2",
      name: "Coffee & errands",
      isArchived: false,
      occasion: "casual",
      isDraft: false,
      itemIds: ["item-1", "item-3", "item-5", "item-7"],
      createdAt: "2026-08-11T10:00:00.000Z",
    },
    {
      id: "outfit-3",
      name: "Dinner, maybe",
      isArchived: false,
      occasion: "date_night",
      isDraft: true,
      itemIds: ["item-2", "item-3", "item-6"],
      createdAt: "2026-08-14T10:00:00.000Z",
    },
  ],
  wearEntries: [
    {
      id: "wear-1",
      date: "2026-08-19",
      occasion: "work",
      outfitId: "outfit-1",
      itemIds: [],
      feeling: "confident",
      note: "Felt put together without trying too hard.",
      createdAt: "2026-08-19T18:00:00.000Z",
    },
    {
      id: "wear-2",
      date: "2026-08-16",
      occasion: "casual",
      outfitId: "outfit-2",
      itemIds: [],
      feeling: "good",
      note: "Comfortable all day; jacket was useful after sunset.",
      createdAt: "2026-08-16T18:00:00.000Z",
    },
  ],
};
