-- Read-only wardrobe sharing: one optional share link per user.
-- Apply to existing Dolaby databases after 20260824000000_add_underwear_category.sql.
-- The token is generated by the app (32 hex characters). Viewing happens
-- through a server API route that validates the token, so this table stays
-- owner-only with no anonymous policies.

create table if not exists public.wardrobe_shares (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  token text not null unique,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.wardrobe_shares enable row level security;

drop policy if exists "wardrobe_shares_owner_all" on public.wardrobe_shares;
create policy "wardrobe_shares_owner_all" on public.wardrobe_shares
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
